
export class Shop {
    static categories = ['skin', 'flag', 'frame']
    static skin = [
        { 'id': 0, name: 'bomber_S1', icon: 'hero/65/2.webp' },
    ]
    static frame = [
        { 'id': 0, name: 'frame_classic', icon: 'frames/1.webp' },
    ]
    static flag = [
        { 'id': 1, 'externalId': 'admin', 'icon': 'flags/admin.png', 'name': 'Админ', 'type': 'adminFlags' },
        { 'id': 2, 'externalId': 'administration', 'icon': 'flags/administration.png', 'name': 'Администрация', 'type': 'adminFlags' },
        { 'id': 3, 'externalId': 'nival', 'icon': 'flags/nival.png', 'name': 'Нивал', 'type': 'adminFlags' },
        { 'id': 4, 'externalId': 'adornia', 'icon': 'flags/adornia.png', 'name': 'Адорнийцы', 'type': 'customFlags' },
        { 'id': 5, 'externalId': 'apple', 'icon': 'flags/apple.png', 'name': 'Фрукт', 'type': 'customFlags' },
        { 'id': 6, 'externalId': 'ball', 'icon': 'flags/ball.png', 'name': 'Футбол', 'type': 'customFlags' },
        { 'id': 7, 'externalId': 'bat', 'icon': 'flags/bat.png', 'name': 'Летучая мышь', 'type': 'customFlags' },
        { 'id': 8, 'externalId': 'bike', 'icon': 'flags/bike.png', 'name': 'Велосипед', 'type': 'customFlags' },
        { 'id': 9, 'externalId': 'casino', 'icon': 'flags/casino.png', 'name': 'Казино', 'type': 'customFlags' },
        { 'id': 10, 'externalId': 'crab', 'icon': 'flags/crab.png', 'name': 'Краб', 'type': 'customFlags' },
        { 'id': 11, 'externalId': 'CSKA', 'icon': 'flags/CSKA.png', 'name': 'Красно-синий', 'type': 'customFlags' },
        { 'id': 12, 'externalId': 'dagger', 'icon': 'flags/dagger.png', 'name': 'Карающий меч', 'type': 'customFlags' },
        { 'id': 13, 'externalId': 'devil', 'icon': 'flags/devil.png', 'name': 'Демон', 'type': 'customFlags' },
        { 'id': 14, 'externalId': 'dokt', 'icon': 'flags/dokt.png', 'name': 'Докты', 'type': 'customFlags' },
        { 'id': 15, 'externalId': 'dragon', 'icon': 'flags/dragon.png', 'name': 'Дракон', 'type': 'customFlags' },
        { 'id': 16, 'externalId': 'fire_sword', 'icon': 'flags/fire_sword.png', 'name': 'Пылающий меч', 'type': 'customFlags' },
        { 'id': 17, 'externalId': 'flower', 'icon': 'flags/flower.png', 'name': 'Тюльпан', 'type': 'customFlags' },
        { 'id': 18, 'externalId': 'fun_smile', 'icon': 'flags/fun_smile.png', 'name': 'Беззубик', 'type': 'customFlags' },
        { 'id': 19, 'externalId': 'hockey', 'icon': 'flags/hockey.png', 'name': 'пятница,13', 'type': 'customFlags' },
        { 'id': 20, 'externalId': 'hypnosis', 'icon': 'flags/hypnosis.png', 'name': 'Гипноз', 'type': 'customFlags' },
        { 'id': 21, 'externalId': 'in_yan', 'icon': 'flags/in_yan.png', 'name': 'Гармония', 'type': 'customFlags' },
        { 'id': 22, 'externalId': 'jedi', 'icon': 'flags/djedai.png', 'name': 'Джедай', 'type': 'customFlags' },
        { 'id': 23, 'externalId': 'kapitoshka', 'icon': 'flags/kapitoshka.png', 'name': 'Капитошка', 'type': 'customFlags' },
        { 'id': 24, 'externalId': 'kote', 'icon': 'flags/kote.png', 'name': 'Кошка', 'type': 'customFlags' },
        { 'id': 25, 'externalId': 'krest', 'icon': 'flags/krest.png', 'name': 'Тевтонский крест', 'type': 'customFlags' },
        { 'id': 26, 'externalId': 'lightning', 'icon': 'flags/lightning.png', 'name': 'Молния', 'type': 'customFlags' },
        { 'id': 27, 'externalId': 'lips', 'icon': 'flags/lips.png', 'name': 'Губки', 'type': 'customFlags' },
        { 'id': 28, 'externalId': 'morkov', 'icon': 'flags/morkov.png', 'name': 'Морковка', 'type': 'customFlags' },
        { 'id': 29, 'externalId': 'no lobster', 'icon': 'flags/no_rak.png', 'name': 'Профи', 'type': 'customFlags' },
        { 'id': 30, 'externalId': 'owl', 'icon': 'flags/owl.png', 'name': 'Сова', 'type': 'customFlags' },
        { 'id': 31, 'externalId': 'packman', 'icon': 'flags/packman.png', 'name': 'Пакман', 'type': 'customFlags' },
        { 'id': 32, 'externalId': 'pautina', 'icon': 'flags/pautina.png', 'name': 'Паутина', 'type': 'customFlags' },
        { 'id': 33, 'externalId': 'peace', 'icon': 'flags/hippie.png', 'name': 'Мир!', 'type': 'customFlags' },
        { 'id': 34, 'externalId': 'pirat', 'icon': 'flags/pirat.png', 'name': 'Пират', 'type': 'customFlags' },
        { 'id': 35, 'externalId': 'prime', 'icon': 'flags/prime.png', 'name': 'Прайм', 'type': 'customFlags' },
        { 'id': 36, 'externalId': 'radiation', 'icon': 'flags/radiation.png', 'name': 'Опасность', 'type': 'customFlags' },
        { 'id': 37, 'externalId': 'rak', 'icon': 'flags/rak.png', 'name': 'Рак', 'type': 'customFlags' },
        { 'id': 38, 'externalId': 'rock', 'icon': 'flags/rock.png', 'name': 'Рок', 'type': 'customFlags' },
        { 'id': 39, 'externalId': 'smile', 'icon': 'flags/smile.png', 'name': 'Всем добра', 'type': 'customFlags' },
        { 'id': 40, 'externalId': 'spartak', 'icon': 'flags/spartak.png', 'name': 'Красно-белый', 'type': 'customFlags' },
        { 'id': 41, 'externalId': 'spoon', 'icon': 'flags/spoon.png', 'name': 'Ложка и вилка', 'type': 'customFlags' },
        { 'id': 42, 'externalId': 'tikva', 'icon': 'flags/tikva.png', 'name': 'Тыква', 'type': 'customFlags' },
        { 'id': 43, 'externalId': 'troll', 'icon': 'flags/troll.png', 'name': 'Тролль', 'type': 'customFlags' },
        { 'id': 44, 'externalId': 'USSR', 'icon': 'flags/USSR.png', 'name': 'СССР', 'type': 'customFlags' },
        { 'id': 45, 'externalId': 'zenit', 'icon': 'flags/zenit.png', 'name': 'Сине-бело-голубой', 'type': 'customFlags' },
        { 'id': 46, 'externalId': 'zubi', 'icon': 'flags/zubi.png', 'name': 'Пасть', 'type': 'customFlags' },
        { 'id': 47, 'externalId': 'x-tree', 'icon': 'flags/x-mas.png', 'name': 'С новым 2015 годом!', 'type': 'customFlags' },
        { 'id': 48, 'externalId': 'bebebe', 'icon': 'flags/sheep.png', 'name': 'Бебебезумие и отвага', 'type': 'customFlags' },
        { 'id': 49, 'externalId': 'nlove', 'icon': 'flags/heart-box.png', 'name': 'Нивал любит тебя!', 'type': 'customFlags' },
        { 'id': 50, 'externalId': 'valentine', 'icon': 'flags/heart.png', 'name': 'Валентинка', 'type': 'customFlags' },
        { 'id': 51, 'externalId': 'medal', 'icon': 'flags/medal.png', 'name': 'Защитник отечества', 'type': 'customFlags' },
        { 'id': 52, 'externalId': 'day23', 'icon': 'flags/23fev.png', 'name': 'С 23 февраля!', 'type': 'customFlags' },
        { 'id': 53, 'externalId': 'shoe', 'icon': 'flags/shoes.png', 'name': 'Туфелька', 'type': 'customFlags' },
        { 'id': 54, 'externalId': 'swallow', 'icon': 'flags/swallow.png', 'name': 'Весна пришла', 'type': 'customFlags' },
        { 'id': 55, 'externalId': 'flower_1', 'icon': 'flags/flower1.png', 'name': 'Цветок', 'type': 'customFlags' },
        { 'id': 56, 'externalId': 'smile_admin', 'icon': 'flags/smile_admin.png', 'name': 'Я видел админов!', 'type': 'customFlags' },
        { 'id': 57, 'externalId': 'smile_boss', 'icon': 'flags/smile_boss.png', 'name': 'Like a boss', 'type': 'customFlags' },
        { 'id': 58, 'externalId': 'silver_league', 'icon': 'flags/Silver.png', 'name': 'Серебряная лига декабрь 2015', 'type': 'customFlags' },
        { 'id': 59, 'externalId': 'golden_league', 'icon': 'flags/Gold.png', 'name': 'Золотая лига декабрь 2015', 'type': 'customFlags' },
        { 'id': 60, 'externalId': 'guide', 'icon': 'flags/guide.png', 'name': 'Гайдомастер', 'type': 'customFlags' },
        { 'id': 61, 'externalId': 'star', 'icon': 'flags/star.png', 'name': 'День Победы', 'type': 'customFlags' },
        { 'id': 62, 'externalId': 'smile_succubus', 'icon': 'flags/succubs.png', 'name': 'Суккубы', 'type': 'customFlags' },
        { 'id': 63, 'externalId': 'season1_simple', 'icon': 'flags/shield_1.png', 'name': 'Щит каменной лиги', 'type': 'customFlags' },
        { 'id': 64, 'externalId': 'season1_bronze', 'icon': 'flags/shield_2.png', 'name': 'Щит бронзовой лиги', 'type': 'customFlags' },
        { 'id': 65, 'externalId': 'season1_silver', 'icon': 'flags/shield_3.png', 'name': 'Щит серебряной лиги', 'type': 'customFlags' },
        { 'id': 66, 'externalId': 'season1_gold', 'icon': 'flags/shield_4.png', 'name': 'Щит золотой лиги', 'type': 'customFlags' },
        { 'id': 67, 'externalId': 'season1_epic', 'icon': 'flags/shield_5.png', 'name': 'Щит легенды', 'type': 'customFlags' },
        { 'id': 68, 'externalId': 'season1Vamp_simple', 'icon': 'flags/cup_01.png', 'name': 'Кубок каменной лиги', 'type': 'customFlags' },
        { 'id': 69, 'externalId': 'season1Vamp_bronze', 'icon': 'flags/cup_02.png', 'name': 'Кубок бронзовой лиги', 'type': 'customFlags' },
        { 'id': 70, 'externalId': 'season1Vamp_silver', 'icon': 'flags/cup_03.png', 'name': 'Кубок серебряной лиги', 'type': 'customFlags' },
        { 'id': 71, 'externalId': 'season1Vamp_gold', 'icon': 'flags/cup_04.png', 'name': 'Кубок золотой лиги', 'type': 'customFlags' },
        { 'id': 72, 'externalId': 'season1Vamp_epic', 'icon': 'flags/cup_05.png', 'name': 'Кубок легенды', 'type': 'customFlags' },
        { 'id': 73, 'externalId': 'season3_simple', 'icon': 'flags/bolt_01.png', 'name': 'Гроза каменной лиги', 'type': 'customFlags' },
        { 'id': 74, 'externalId': 'season3_bronze', 'icon': 'flags/bolt_02.png', 'name': 'Гроза бронзовой лиги', 'type': 'customFlags' },
        { 'id': 75, 'externalId': 'season3_silver', 'icon': 'flags/bolt_03.png', 'name': 'Гроза серебряной лиги', 'type': 'customFlags' },
        { 'id': 76, 'externalId': 'season3_gold', 'icon': 'flags/bolt_04.png', 'name': 'Гроза золотой лиги', 'type': 'customFlags' },
        { 'id': 77, 'externalId': 'season3_epic', 'icon': 'flags/bolt_05.png', 'name': 'Гроза легенды', 'type': 'customFlags' },
        { 'id': 78, 'externalId': 'season4_simple', 'icon': 'flags/fire_01.png', 'name': 'Пламя каменной лиги', 'type': 'customFlags' },
        { 'id': 79, 'externalId': 'season4_bronze', 'icon': 'flags/fire_02.png', 'name': 'Пламя бронзовой лиги', 'type': 'customFlags' },
        { 'id': 80, 'externalId': 'season4_silver', 'icon': 'flags/fire_03.png', 'name': 'Пламя серебряной лиги', 'type': 'customFlags' },
        { 'id': 81, 'externalId': 'season4_gold', 'icon': 'flags/fire_04.png', 'name': 'Пламя золотой лиги', 'type': 'customFlags' },
        { 'id': 82, 'externalId': 'season4_epic', 'icon': 'flags/fire_05.png', 'name': 'Легендарное пламя', 'type': 'customFlags' },
        { 'id': 83, 'externalId': 'helper', 'icon': 'flags/helper.png', 'name': 'Они следят за тобой', 'type': 'customFlags' },
        { 'id': 84, 'externalId': 'season5_simple', 'icon': 'flags/flags_Gems_60x60_01.png', 'name': 'Самоцвет каменной лиги', 'type': 'customFlags' },
        { 'id': 85, 'externalId': 'season5_bronze', 'icon': 'flags/flags_Gems_60x60_02.png', 'name': 'Самоцвет бронзовой лиги', 'type': 'customFlags' },
        { 'id': 86, 'externalId': 'season5_silver', 'icon': 'flags/flags_Gems_60x60_03.png', 'name': 'Самоцвет серебряной лиги', 'type': 'customFlags' },
        { 'id': 87, 'externalId': 'season5_gold', 'icon': 'flags/flags_Gems_60x60_04.png', 'name': 'Самоцвет золотой лиги', 'type': 'customFlags' },
        { 'id': 88, 'externalId': 'season5_epic', 'icon': 'flags/flags_Gems_60x60_05.png', 'name': 'Легендарный самоцвет', 'type': 'customFlags' },
        { 'id': 89, 'externalId': 'season6_simple', 'icon': 'flags/flags_Chains_60x60_01.png', 'name': 'Страж каменной лиги', 'type': 'customFlags' },
        { 'id': 90, 'externalId': 'season6_bronze', 'icon': 'flags/flags_Chains_60x60_02.png', 'name': 'Страж бронзовой лиги', 'type': 'customFlags' },
        { 'id': 91, 'externalId': 'season6_silver', 'icon': 'flags/flags_Chains_60x60_03.png', 'name': 'Страж серебряной лиги', 'type': 'customFlags' },
        { 'id': 92, 'externalId': 'season6_gold', 'icon': 'flags/flags_Chains_60x60_04.png', 'name': 'Страж золотой лиги', 'type': 'customFlags' },
        { 'id': 93, 'externalId': 'season6_epic', 'icon': 'flags/flags_Chains_60x60_05.png', 'name': 'Легендарный страж', 'type': 'customFlags' },
        { 'id': 94, 'externalId': 'season7_simple', 'icon': 'flags/flags_Mask_60x60_1.png', 'name': 'Мираж каменной лиги', 'type': 'customFlags' },
        { 'id': 95, 'externalId': 'season7_bronze', 'icon': 'flags/flags_Mask_60x60_2.png', 'name': 'Мираж бронзовой лиги', 'type': 'customFlags' },
        { 'id': 96, 'externalId': 'season7_silver', 'icon': 'flags/flags_Mask_60x60_3.png', 'name': 'Мираж серебряной лиги', 'type': 'customFlags' },
        { 'id': 97, 'externalId': 'season7_gold', 'icon': 'flags/flags_Mask_60x60_4.png', 'name': 'Мираж золотой лиги', 'type': 'customFlags' },
        { 'id': 98, 'externalId': 'season7_epic', 'icon': 'flags/flags_Mask_60x60_5.png', 'name': 'Легендарный мираж', 'type': 'customFlags' },
        { 'id': 99, 'externalId': 'season8_simple', 'icon': 'flags/flags_Dragon_60x60_01.png', 'name': 'Дракон каменной лиги', 'type': 'customFlags' },
        { 'id': 100, 'externalId': 'season8_bronze', 'icon': 'flags/flags_Dragon_60x60_02.png', 'name': 'Дракон бронзовой лиги', 'type': 'customFlags' },
        { 'id': 101, 'externalId': 'season8_silver', 'icon': 'flags/flags_Dragon_60x60_03.png', 'name': 'Дракон серебряной лиги', 'type': 'customFlags' },
        { 'id': 102, 'externalId': 'season8_gold', 'icon': 'flags/flags_Dragon_60x60_04.png', 'name': 'Дракон золотой лиги', 'type': 'customFlags' },
        { 'id': 103, 'externalId': 'season8_epic', 'icon': 'flags/flags_Dragon_60x60_05.png', 'name': 'Легендарный дракон', 'type': 'customFlags' },
        { 'id': 104, 'externalId': 'season9', 'icon': 'flags/flags_Final_60x60_05.png', 'name': 'Сезон Древних', 'type': 'customFlags' },
        { 'id': 105, 'externalId': 'tournament2019_1', 'icon': 'flags/tournament2019_1.png', 'name': 'Кубок Праи: Божество', 'type': 'customFlags' },
        { 'id': 106, 'externalId': 'tournament2019_2', 'icon': 'flags/tournament2019_2.png', 'name': 'Кубок Праи: Полубог', 'type': 'customFlags' },
        { 'id': 107, 'externalId': 'tournament2019_3', 'icon': 'flags/tournament2019_3.png', 'name': 'Кубок Праи: Легенда', 'type': 'customFlags' },
        { 'id': 108, 'externalId': 'tournament2019_4', 'icon': 'flags/tournament2019_4.png', 'name': 'Кубок Праи: Герой', 'type': 'customFlags' },
        { 'id': 109, 'externalId': 'tournament2019_5', 'icon': 'flags/tournament2019_5.png', 'name': 'Кубок Праи: Храбрец', 'type': 'customFlags' },
        { 'id': 110, 'externalId': 'st_bronze', 'icon': 'flags/st_bronze.png', 'name': 'Бронза неофициального турнира', 'type': 'customFlags' },
        { 'id': 111, 'externalId': 'st_silver', 'icon': 'flags/st_silver.png', 'name': 'Серебро неофициального турнира', 'type': 'customFlags' },
        { 'id': 112, 'externalId': 'st_gold', 'icon': 'flags/st_gold.png', 'name': 'Золото неофициального турнира', 'type': 'customFlags' },
        { 'id': 113, 'externalId': 'season10', 'icon': 'flags/flag_season_60x60.png', 'name': 'Сезон Каменьев', 'type': 'customFlags' },
        { 'id': 114, 'externalId': 'grdv_bronze', 'icon': 'flags/grdv_3.png', 'name': 'Гридвальдский фестиваль: Бронза', 'type': 'customFlags' },
        { 'id': 115, 'externalId': 'grdv_silver', 'icon': 'flags/grdv_2.png', 'name': 'Гридвальдский фестиваль: Серебро', 'type': 'customFlags' },
        { 'id': 116, 'externalId': 'grdv_gold', 'icon': 'flags/grdv_1.png', 'name': 'Гридвальдский фестиваль: Золото', 'type': 'customFlags' },
        { 'id': 117, 'externalId': 'season11', 'icon': 'flags/Reznya.png', 'name': 'Сезон Резни', 'type': 'customFlags' },
        { 'id': 118, 'externalId': 'hw_1', 'icon': 'flags/hw_1.png', 'name': 'Бу!', 'type': 'customFlags' },
        { 'id': 119, 'externalId': 'hw_2', 'icon': 'flags/hw_2.png', 'name': 'Угроза', 'type': 'customFlags' },
        { 'id': 120, 'externalId': 'hw_3', 'icon': 'flags/hw_3.png', 'name': 'Рукопожатие', 'type': 'customFlags' },
        { 'id': 121, 'externalId': 'hw_4', 'icon': 'flags/hw_4.png', 'name': 'Тишина', 'type': 'customFlags' },
        { 'id': 122, 'externalId': 'hw_5', 'icon': 'flags/hw_5.png', 'name': 'Хеллоуинский мишка', 'type': 'customFlags' },
        { 'id': 123, 'externalId': 'season12', 'icon': 'flags/LAVA_flag.png', 'name': 'Сезон Лавы', 'type': 'customFlags' },
        { 'id': 124, 'externalId': 'omnika', 'icon': 'flags/omnika.png', 'name': 'Свет утренней звезды', 'type': 'customFlags' },
        { 'id': 125, 'externalId': '3776', 'icon': 'flags/3776_fin.png', 'name': 'Единорожек', 'type': 'customFlags' },
        { 'id': 126, 'externalId': 'season13', 'icon': 'flags/moon_flag.png', 'name': 'Сезон Сновидений', 'type': 'customFlags' },
        { 'id': 127, 'externalId': 'lantarm', 'icon': 'flags/lantarm.png', 'name': 'Лунная призма, дай мне силу!\n', 'type': 'customFlags' },
        { 'id': 128, 'externalId': 'solo_1', 'icon': 'flags/solo_1.png', 'name': 'Золото SOLO турнира', 'type': 'customFlags' },
        { 'id': 129, 'externalId': 'solo_2', 'icon': 'flags/solo_2.png', 'name': 'Серебро SOLO турнира', 'type': 'customFlags' },
        { 'id': 130, 'externalId': 'solo_3', 'icon': 'flags/solo_3.png', 'name': 'Бронза SOLO турнира', 'type': 'customFlags' },
        { 'id': 131, 'externalId': 'lostinthedark', 'icon': 'flags/Lostinthedark.png', 'name': 'Лисичка', 'type': 'customFlags' },
        { 'id': 132, 'externalId': 'lostinthedark2', 'icon': 'flags/Lostinthedark2.png', 'name': 'Бисквит', 'type': 'customFlags' },
        { 'id': 133, 'externalId': 'xleox', 'icon': 'flags/XLeoX.png', 'name': 'XLeoX', 'type': 'customFlags' },
        { 'id': 134, 'externalId': 'season14', 'icon': 'flags/season14.png', 'name': 'Сезон Технологий', 'type': 'customFlags' },
        { 'id': 135, 'externalId': 'NA', 'icon': 'flags/NA.png', 'name': 'Рейтинг это просто цифры', 'type': 'customFlags' },
        { 'id': 136, 'externalId': 'fox1', 'icon': 'flags/fox1.png', 'name': 'Лисий хвост', 'type': 'customFlags' },
        { 'id': 137, 'externalId': 'season15', 'icon': 'flags/season15.png', 'name': 'Сезон Колдовства', 'type': 'customFlags' },
        { 'id': 138, 'externalId': 'season16', 'icon': 'flags/season16.png', 'name': 'Сезон Прогресса', 'type': 'customFlags' },
        { 'id': 139, 'externalId': 'default_flag', 'icon': 'flags/default.png', 'name': 'Неизвестный флаг', 'type': 'countryFlags' },
        { 'id': 140, 'externalId': 'andorra', 'icon': 'flags/andorra.png', 'name': 'Андорра', 'type': 'countryFlags' },
        { 'id': 141, 'externalId': 'albania', 'icon': 'flags/albania.png', 'name': 'Албания', 'type': 'countryFlags' },
        { 'id': 142, 'externalId': 'armenia', 'icon': 'flags/armenia.png', 'name': 'Армения', 'type': 'countryFlags' },
        { 'id': 143, 'externalId': 'argentina', 'icon': 'flags/argentina.png', 'name': 'Аргентина', 'type': 'countryFlags' },
        { 'id': 144, 'externalId': 'austria', 'icon': 'flags/austria.png', 'name': 'Австрия', 'type': 'countryFlags' },
        { 'id': 145, 'externalId': 'australia', 'icon': 'flags/australia.png', 'name': 'Австралия', 'type': 'countryFlags' },
        { 'id': 146, 'externalId': 'azerbaijan', 'icon': 'flags/azerbaijan.png', 'name': 'Азербайджан', 'type': 'countryFlags' },
        { 'id': 147, 'externalId': 'bosnia_and_herzegovina', 'icon': 'flags/bosnia_and_herzegovina.png', 'name': 'Босния и Герцеговина', 'type': 'countryFlags' },
        { 'id': 148, 'externalId': 'belgium', 'icon': 'flags/belgium.png', 'name': 'Бельгия', 'type': 'countryFlags' },
        { 'id': 149, 'externalId': 'bulgaria', 'icon': 'flags/bulgaria.png', 'name': 'Болгария', 'type': 'countryFlags' },
        { 'id': 150, 'externalId': 'brazil', 'icon': 'flags/brazil.png', 'name': 'Бразилия', 'type': 'countryFlags' },
        { 'id': 151, 'externalId': 'belarus', 'icon': 'flags/belarus.png', 'name': 'Беларусь', 'type': 'countryFlags' },
        { 'id': 152, 'externalId': 'canada', 'icon': 'flags/canada.png', 'name': 'Канада', 'type': 'countryFlags' },
        { 'id': 153, 'externalId': 'switzerland', 'icon': 'flags/switzerland.png', 'name': 'Швейцария', 'type': 'countryFlags' },
        { 'id': 154, 'externalId': 'cyprus', 'icon': 'flags/cyprus.png', 'name': 'Кипр', 'type': 'countryFlags' },
        { 'id': 155, 'externalId': 'czech_republic', 'icon': 'flags/czech_republic.png', 'name': 'Чехия', 'type': 'countryFlags' },
        { 'id': 156, 'externalId': 'germany', 'icon': 'flags/germany.png', 'name': 'Германия', 'type': 'countryFlags' },
        { 'id': 157, 'externalId': 'denmark', 'icon': 'flags/denmark.png', 'name': 'Дания', 'type': 'countryFlags' },
        { 'id': 158, 'externalId': 'estonia', 'icon': 'flags/estonia.png', 'name': 'Эстония', 'type': 'countryFlags' },
        { 'id': 159, 'externalId': 'spain', 'icon': 'flags/spain.png', 'name': 'Испания', 'type': 'countryFlags' },
        { 'id': 160, 'externalId': 'finland', 'icon': 'flags/finland.png', 'name': 'Финляндия', 'type': 'countryFlags' },
        { 'id': 161, 'externalId': 'france', 'icon': 'flags/france.png', 'name': 'Франция', 'type': 'countryFlags' },
        { 'id': 162, 'externalId': 'united_kingdom', 'icon': 'flags/united_kingdom.png', 'name': 'Великобритания', 'type': 'countryFlags' },
        { 'id': 163, 'externalId': 'georgia', 'icon': 'flags/georgia.png', 'name': 'Грузия', 'type': 'countryFlags' },
        { 'id': 164, 'externalId': 'greece', 'icon': 'flags/greece.png', 'name': 'Греция', 'type': 'countryFlags' },
        { 'id': 165, 'externalId': 'croatia', 'icon': 'flags/croatia.png', 'name': 'Хорватия', 'type': 'countryFlags' },
        { 'id': 166, 'externalId': 'hungary', 'icon': 'flags/hungary.png', 'name': 'Венгрия', 'type': 'countryFlags' },
        { 'id': 167, 'externalId': 'ireland', 'icon': 'flags/ireland.png', 'name': 'Ирландия', 'type': 'countryFlags' },
        { 'id': 168, 'externalId': 'israel', 'icon': 'flags/israel.png', 'name': 'Израиль', 'type': 'countryFlags' },
        { 'id': 169, 'externalId': 'iceland', 'icon': 'flags/iceland.png', 'name': 'Исландия', 'type': 'countryFlags' },
        { 'id': 170, 'externalId': 'italy', 'icon': 'flags/italy.png', 'name': 'Италия', 'type': 'countryFlags' },
        { 'id': 171, 'externalId': 'kyrgyzstan', 'icon': 'flags/kyrgyzstan.png', 'name': 'Кыргызстан', 'type': 'countryFlags' },
        { 'id': 172, 'externalId': 'china', 'icon': 'flags/china.png', 'name': 'Китай', 'type': 'countryFlags' },
        { 'id': 173, 'externalId': 'kazakhstan', 'icon': 'flags/kazakhstan.png', 'name': 'Казахстан', 'type': 'countryFlags' },
        { 'id': 174, 'externalId': 'liechtenstein', 'icon': 'flags/liechtenstein.png', 'name': 'Лихтенштейн', 'type': 'countryFlags' },
        { 'id': 175, 'externalId': 'lithuania', 'icon': 'flags/lithuania.png', 'name': 'Литва', 'type': 'countryFlags' },
        { 'id': 176, 'externalId': 'luxembourg', 'icon': 'flags/luxembourg.png', 'name': 'Люксембург', 'type': 'countryFlags' },
        { 'id': 177, 'externalId': 'latvia', 'icon': 'flags/latvia.png', 'name': 'Латвия', 'type': 'countryFlags' },
        { 'id': 178, 'externalId': 'monaco', 'icon': 'flags/monaco.png', 'name': 'Монако', 'type': 'countryFlags' },
        { 'id': 179, 'externalId': 'moldova', 'icon': 'flags/moldova.png', 'name': 'Молдова', 'type': 'countryFlags' },
        { 'id': 180, 'externalId': 'montenegro', 'icon': 'flags/montenegro.png', 'name': 'Черногория', 'type': 'countryFlags' },
        { 'id': 181, 'externalId': 'macedonia', 'icon': 'flags/macedonia.png', 'name': 'Македония', 'type': 'countryFlags' },
        { 'id': 182, 'externalId': 'malta', 'icon': 'flags/malta.png', 'name': 'Мальта', 'type': 'countryFlags' },
        { 'id': 183, 'externalId': 'mexico', 'icon': 'flags/mexico.png', 'name': 'Мексика', 'type': 'countryFlags' },
        { 'id': 184, 'externalId': 'netherlands', 'icon': 'flags/netherlands.png', 'name': 'Нидерланды', 'type': 'countryFlags' },
        { 'id': 185, 'externalId': 'norway', 'icon': 'flags/norway.png', 'name': 'Норвегия', 'type': 'countryFlags' },
        { 'id': 186, 'externalId': 'new_zealand', 'icon': 'flags/new_zealand.png', 'name': 'Новая Зеландия', 'type': 'countryFlags' },
        { 'id': 187, 'externalId': 'philippines', 'icon': 'flags/philippines.png', 'name': 'Филиппины', 'type': 'countryFlags' },
        { 'id': 188, 'externalId': 'poland', 'icon': 'flags/poland.png', 'name': 'Польша', 'type': 'countryFlags' },
        { 'id': 189, 'externalId': 'portugal', 'icon': 'flags/portugal.png', 'name': 'Португалия', 'type': 'countryFlags' },
        { 'id': 190, 'externalId': 'romania', 'icon': 'flags/romania.png', 'name': 'Румыния', 'type': 'countryFlags' },
        { 'id': 191, 'externalId': 'serbia', 'icon': 'flags/serbia.png', 'name': 'Сербия', 'type': 'countryFlags' },
        { 'id': 192, 'externalId': 'russia', 'icon': 'flags/russia.png', 'name': 'Россия', 'type': 'countryFlags' },
        { 'id': 193, 'externalId': 'sweden', 'icon': 'flags/sweden.png', 'name': 'Швеция', 'type': 'countryFlags' },
        { 'id': 194, 'externalId': 'slovenia', 'icon': 'flags/slovenia.png', 'name': 'Словения', 'type': 'countryFlags' },
        { 'id': 195, 'externalId': 'slovakia', 'icon': 'flags/slovakia.png', 'name': 'Словакия', 'type': 'countryFlags' },
        { 'id': 196, 'externalId': 'san_marino', 'icon': 'flags/san_marino.png', 'name': 'Сан-Марино', 'type': 'countryFlags' },
        { 'id': 197, 'externalId': 'tajikistan', 'icon': 'flags/tajikistan.png', 'name': 'Таджикистан', 'type': 'countryFlags' },
        { 'id': 198, 'externalId': 'turkmenistan', 'icon': 'flags/turkmenistan.png', 'name': 'Туркменистан', 'type': 'countryFlags' },
        { 'id': 199, 'externalId': 'turkey', 'icon': 'flags/turkey.png', 'name': 'Турция', 'type': 'countryFlags' },
        { 'id': 200, 'externalId': 'ukraine', 'icon': 'flags/ukraine.png', 'name': 'Украина', 'type': 'countryFlags' },
        { 'id': 201, 'externalId': 'united_states', 'icon': 'flags/united_states_of_america.png', 'name': 'США', 'type': 'countryFlags' },
        { 'id': 202, 'externalId': 'uzbekistan', 'icon': 'flags/uzbekistan.png', 'name': 'Узбекистан', 'type': 'countryFlags' },
        { 'id': 203, 'externalId': 'vatican', 'icon': 'flags/vatican_city.png', 'name': 'Ватикан', 'type': 'countryFlags' },
        { 'id': 204, 'externalId': 'vietnam', 'icon': 'flags/vietnam.png', 'name': 'Вьетнам', 'type': 'countryFlags' },
        { 'id': 205, 'externalId': 'south_afrika', 'icon': 'flags/south_africa.png', 'name': 'Южная Африка', 'type': 'countryFlags' },
        { 'id': 206, 'externalId': 'jamaica', 'icon': 'flags/jamaica.png', 'name': 'Ямайка', 'type': 'countryFlags' },
        { 'id': 207, 'externalId': 'japan', 'icon': 'flags/japan.png', 'name': 'Япония', 'type': 'countryFlags' },
        { 'id': 208, 'externalId': 'chile', 'icon': 'flags/chili.png', 'name': 'Чили', 'type': 'countryFlags' },
        { 'id': 209, 'externalId': 'mozambique', 'icon': 'flags/Mozambique.png', 'name': 'Мозамбик', 'type': 'countryFlags' },
    ]
}