import { App } from './app.js';

export class Shop {
    static categories = {
        1: 'flag',
        2: 'frame',
        3: 'skin',
    }

    static getIcon(categoryId, externalId) {
        switch (categoryId) {
            case 1:
                return Shop.getFlagIcon(externalId);
            case 2:
                return Shop.getFrameIcon(externalId);
            case 3:
                return Shop.getSkinIcon(externalId);
            default:
                App.error(`Некорректный categoryId ${categoryId} для предмета ${externalId}`);
                return [''];
        }
    }
    static getFlagIcon(externalId) {
        return [`url("content/flags/${externalId}.png")`];
    }
    static getFrameIcon(externalId) {
        let frameType_frameId = externalId.split('/');
        let frameType = Number(frameType_frameId[0]);
        let frameId = Math.max(0, Number(frameType_frameId[1]) - 1);
        return [`url("content/frames/${frameType + frameId}.png")`];
    }
    static getSkinIcon(externalId) {
        let heroId_skinId = externalId.split('/');
        let heroId = heroId_skinId[0];
        let skinId = heroId_skinId[1];
        return [`url("content/hero/${heroId}/${skinId}.webp")`, `url("content/hero/${heroId}/1.webp")`];
    }

    static getName(categoryId, externalId) {
        if (categoryId == 3) {
            let heroId_skinId = externalId.split('/');
            let heroId = heroId_skinId[0];
            let skinId = heroId_skinId[1];
            let name = `hero_${heroId}_skin_${skinId}_name`;
            let srcName = `hero_${heroId}_name`;
            return [name, srcName];
        }
        return [`${this.categories[categoryId]}_${externalId.replace('/', '_')}`]
    }
    static shopItems = [
        {},
        { 'categoryId': 2, 'name': 'frame_0', 'icon': 'frames/0_' },
        { 'categoryId': 2, 'name': 'frame_1', 'icon': 'frames/1_' },
        { 'categoryId': 2, 'name': 'frame_2', 'icon': 'frames/2_' },
        { 'categoryId': 2, 'name': 'frame_3', 'icon': 'frames/3_' },
        { 'categoryId': 2, 'name': 'frame_4', 'icon': 'frames/4_' },
        { 'categoryId': 2, 'name': 'frame_5', 'icon': 'frames/5_' },
        { 'categoryId': 2, 'name': 'frame_6', 'icon': 'frames/6_' },
        { 'categoryId': 2, 'name': 'frame_7', 'icon': 'frames/7_' },
        { 'categoryId': 2, 'name': 'frame_8', 'icon': 'frames/8_' },
        
        { 'categoryId': 1, 'externalId': 'admin', 'icon': 'flags/admin.png', 'name': 'Админ', 'type': 'adminFlags' },
        { 'categoryId': 1, 'externalId': 'administration', 'icon': 'flags/administration.png', 'name': 'Администрация', 'type': 'adminFlags' },
        { 'categoryId': 1, 'externalId': 'nival', 'icon': 'flags/nival.png', 'name': 'Нивал', 'type': 'adminFlags' },
        { 'categoryId': 1, 'externalId': 'adornia', 'icon': 'flags/adornia.png', 'name': 'Адорнийцы', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'apple', 'icon': 'flags/apple.png', 'name': 'Фрукт', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'ball', 'icon': 'flags/ball.png', 'name': 'Футбол', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'bat', 'icon': 'flags/bat.png', 'name': 'Летучая мышь', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'bike', 'icon': 'flags/bike.png', 'name': 'Велосипед', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'casino', 'icon': 'flags/casino.png', 'name': 'Казино', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'crab', 'icon': 'flags/crab.png', 'name': 'Краб', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'CSKA', 'icon': 'flags/CSKA.png', 'name': 'Красно-синий', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'dagger', 'icon': 'flags/dagger.png', 'name': 'Карающий меч', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'devil', 'icon': 'flags/devil.png', 'name': 'Демон', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'dokt', 'icon': 'flags/dokt.png', 'name': 'Докты', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'dragon', 'icon': 'flags/dragon.png', 'name': 'Дракон', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'fire_sword', 'icon': 'flags/fire_sword.png', 'name': 'Пылающий меч', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'flower', 'icon': 'flags/flower.png', 'name': 'Тюльпан', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'fun_smile', 'icon': 'flags/fun_smile.png', 'name': 'Беззубик', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'hockey', 'icon': 'flags/hockey.png', 'name': 'пятница,13', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'hypnosis', 'icon': 'flags/hypnosis.png', 'name': 'Гипноз', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'in_yan', 'icon': 'flags/in_yan.png', 'name': 'Гармония', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'jedi', 'icon': 'flags/djedai.png', 'name': 'Джедай', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'kapitoshka', 'icon': 'flags/kapitoshka.png', 'name': 'Капитошка', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'kote', 'icon': 'flags/kote.png', 'name': 'Кошка', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'krest', 'icon': 'flags/krest.png', 'name': 'Тевтонский крест', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'lightning', 'icon': 'flags/lightning.png', 'name': 'Молния', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'lips', 'icon': 'flags/lips.png', 'name': 'Губки', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'morkov', 'icon': 'flags/morkov.png', 'name': 'Морковка', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'no lobster', 'icon': 'flags/no_rak.png', 'name': 'Профи', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'owl', 'icon': 'flags/owl.png', 'name': 'Сова', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'packman', 'icon': 'flags/packman.png', 'name': 'Пакман', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'pautina', 'icon': 'flags/pautina.png', 'name': 'Паутина', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'peace', 'icon': 'flags/hippie.png', 'name': 'Мир!', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'pirat', 'icon': 'flags/pirat.png', 'name': 'Пират', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'prime', 'icon': 'flags/prime.png', 'name': 'Прайм', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'radiation', 'icon': 'flags/radiation.png', 'name': 'Опасность', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'rak', 'icon': 'flags/rak.png', 'name': 'Рак', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'rock', 'icon': 'flags/rock.png', 'name': 'Рок', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'smile', 'icon': 'flags/smile.png', 'name': 'Всем добра', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'spartak', 'icon': 'flags/spartak.png', 'name': 'Красно-белый', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'spoon', 'icon': 'flags/spoon.png', 'name': 'Ложка и вилка', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'tikva', 'icon': 'flags/tikva.png', 'name': 'Тыква', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'troll', 'icon': 'flags/troll.png', 'name': 'Тролль', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'USSR', 'icon': 'flags/USSR.png', 'name': 'СССР', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'zenit', 'icon': 'flags/zenit.png', 'name': 'Сине-бело-голубой', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'zubi', 'icon': 'flags/zubi.png', 'name': 'Пасть', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'x-tree', 'icon': 'flags/x-mas.png', 'name': 'С новым 2015 годом!', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'bebebe', 'icon': 'flags/sheep.png', 'name': 'Бебебезумие и отвага', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'nlove', 'icon': 'flags/heart-box.png', 'name': 'Нивал любит тебя!', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'valentine', 'icon': 'flags/heart.png', 'name': 'Валентинка', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'medal', 'icon': 'flags/medal.png', 'name': 'Защитник отечества', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'day23', 'icon': 'flags/23fev.png', 'name': 'С 23 февраля!', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'shoe', 'icon': 'flags/shoes.png', 'name': 'Туфелька', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'swallow', 'icon': 'flags/swallow.png', 'name': 'Весна пришла', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'flower_1', 'icon': 'flags/flower1.png', 'name': 'Цветок', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'smile_admin', 'icon': 'flags/smile_admin.png', 'name': 'Я видел админов!', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'smile_boss', 'icon': 'flags/smile_boss.png', 'name': 'Like a boss', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'silver_league', 'icon': 'flags/Silver.png', 'name': 'Серебряная лига декабрь 2015', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'golden_league', 'icon': 'flags/Gold.png', 'name': 'Золотая лига декабрь 2015', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'guide', 'icon': 'flags/guide.png', 'name': 'Гайдомастер', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'star', 'icon': 'flags/star.png', 'name': 'День Победы', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'smile_succubus', 'icon': 'flags/succubs.png', 'name': 'Суккубы', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season1_simple', 'icon': 'flags/shield_1.png', 'name': 'Щит каменной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season1_bronze', 'icon': 'flags/shield_2.png', 'name': 'Щит бронзовой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season1_silver', 'icon': 'flags/shield_3.png', 'name': 'Щит серебряной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season1_gold', 'icon': 'flags/shield_4.png', 'name': 'Щит золотой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season1_epic', 'icon': 'flags/shield_5.png', 'name': 'Щит легенды', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season1Vamp_simple', 'icon': 'flags/cup_01.png', 'name': 'Кубок каменной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season1Vamp_bronze', 'icon': 'flags/cup_02.png', 'name': 'Кубок бронзовой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season1Vamp_silver', 'icon': 'flags/cup_03.png', 'name': 'Кубок серебряной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season1Vamp_gold', 'icon': 'flags/cup_04.png', 'name': 'Кубок золотой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season1Vamp_epic', 'icon': 'flags/cup_05.png', 'name': 'Кубок легенды', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season3_simple', 'icon': 'flags/bolt_01.png', 'name': 'Гроза каменной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season3_bronze', 'icon': 'flags/bolt_02.png', 'name': 'Гроза бронзовой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season3_silver', 'icon': 'flags/bolt_03.png', 'name': 'Гроза серебряной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season3_gold', 'icon': 'flags/bolt_04.png', 'name': 'Гроза золотой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season3_epic', 'icon': 'flags/bolt_05.png', 'name': 'Гроза легенды', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season4_simple', 'icon': 'flags/fire_01.png', 'name': 'Пламя каменной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season4_bronze', 'icon': 'flags/fire_02.png', 'name': 'Пламя бронзовой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season4_silver', 'icon': 'flags/fire_03.png', 'name': 'Пламя серебряной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season4_gold', 'icon': 'flags/fire_04.png', 'name': 'Пламя золотой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season4_epic', 'icon': 'flags/fire_05.png', 'name': 'Легендарное пламя', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'helper', 'icon': 'flags/helper.png', 'name': 'Они следят за тобой', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season5_simple', 'icon': 'flags/flags_Gems_60x60_01.png', 'name': 'Самоцвет каменной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season5_bronze', 'icon': 'flags/flags_Gems_60x60_02.png', 'name': 'Самоцвет бронзовой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season5_silver', 'icon': 'flags/flags_Gems_60x60_03.png', 'name': 'Самоцвет серебряной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season5_gold', 'icon': 'flags/flags_Gems_60x60_04.png', 'name': 'Самоцвет золотой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season5_epic', 'icon': 'flags/flags_Gems_60x60_05.png', 'name': 'Легендарный самоцвет', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season6_simple', 'icon': 'flags/flags_Chains_60x60_01.png', 'name': 'Страж каменной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season6_bronze', 'icon': 'flags/flags_Chains_60x60_02.png', 'name': 'Страж бронзовой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season6_silver', 'icon': 'flags/flags_Chains_60x60_03.png', 'name': 'Страж серебряной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season6_gold', 'icon': 'flags/flags_Chains_60x60_04.png', 'name': 'Страж золотой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season6_epic', 'icon': 'flags/flags_Chains_60x60_05.png', 'name': 'Легендарный страж', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season7_simple', 'icon': 'flags/flags_Mask_60x60_1.png', 'name': 'Мираж каменной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season7_bronze', 'icon': 'flags/flags_Mask_60x60_2.png', 'name': 'Мираж бронзовой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season7_silver', 'icon': 'flags/flags_Mask_60x60_3.png', 'name': 'Мираж серебряной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season7_gold', 'icon': 'flags/flags_Mask_60x60_4.png', 'name': 'Мираж золотой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season7_epic', 'icon': 'flags/flags_Mask_60x60_5.png', 'name': 'Легендарный мираж', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season8_simple', 'icon': 'flags/flags_Dragon_60x60_01.png', 'name': 'Дракон каменной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season8_bronze', 'icon': 'flags/flags_Dragon_60x60_02.png', 'name': 'Дракон бронзовой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season8_silver', 'icon': 'flags/flags_Dragon_60x60_03.png', 'name': 'Дракон серебряной лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season8_gold', 'icon': 'flags/flags_Dragon_60x60_04.png', 'name': 'Дракон золотой лиги', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season8_epic', 'icon': 'flags/flags_Dragon_60x60_05.png', 'name': 'Легендарный дракон', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season9', 'icon': 'flags/flags_Final_60x60_05.png', 'name': 'Сезон Древних', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'tournament2019_1', 'icon': 'flags/tournament2019_1.png', 'name': 'Кубок Праи: Божество', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'tournament2019_2', 'icon': 'flags/tournament2019_2.png', 'name': 'Кубок Праи: Полубог', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'tournament2019_3', 'icon': 'flags/tournament2019_3.png', 'name': 'Кубок Праи: Легенда', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'tournament2019_4', 'icon': 'flags/tournament2019_4.png', 'name': 'Кубок Праи: Герой', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'tournament2019_5', 'icon': 'flags/tournament2019_5.png', 'name': 'Кубок Праи: Храбрец', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'st_bronze', 'icon': 'flags/st_bronze.png', 'name': 'Бронза неофициального турнира', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'st_silver', 'icon': 'flags/st_silver.png', 'name': 'Серебро неофициального турнира', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'st_gold', 'icon': 'flags/st_gold.png', 'name': 'Золото неофициального турнира', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season10', 'icon': 'flags/flag_season_60x60.png', 'name': 'Сезон Каменьев', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'grdv_bronze', 'icon': 'flags/grdv_3.png', 'name': 'Гридвальдский фестиваль: Бронза', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'grdv_silver', 'icon': 'flags/grdv_2.png', 'name': 'Гридвальдский фестиваль: Серебро', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'grdv_gold', 'icon': 'flags/grdv_1.png', 'name': 'Гридвальдский фестиваль: Золото', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season11', 'icon': 'flags/Reznya.png', 'name': 'Сезон Резни', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'hw_1', 'icon': 'flags/hw_1.png', 'name': 'Бу!', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'hw_2', 'icon': 'flags/hw_2.png', 'name': 'Угроза', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'hw_3', 'icon': 'flags/hw_3.png', 'name': 'Рукопожатие', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'hw_4', 'icon': 'flags/hw_4.png', 'name': 'Тишина', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'hw_5', 'icon': 'flags/hw_5.png', 'name': 'Хеллоуинский мишка', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season12', 'icon': 'flags/LAVA_flag.png', 'name': 'Сезон Лавы', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'omnika', 'icon': 'flags/omnika.png', 'name': 'Свет утренней звезды', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': '3776', 'icon': 'flags/3776_fin.png', 'name': 'Единорожек', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season13', 'icon': 'flags/moon_flag.png', 'name': 'Сезон Сновидений', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'lantarm', 'icon': 'flags/lantarm.png', 'name': 'Лунная призма, дай мне силу!\n', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'solo_1', 'icon': 'flags/solo_1.png', 'name': 'Золото SOLO турнира', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'solo_2', 'icon': 'flags/solo_2.png', 'name': 'Серебро SOLO турнира', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'solo_3', 'icon': 'flags/solo_3.png', 'name': 'Бронза SOLO турнира', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'lostinthedark', 'icon': 'flags/Lostinthedark.png', 'name': 'Лисичка', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'lostinthedark2', 'icon': 'flags/Lostinthedark2.png', 'name': 'Бисквит', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'xleox', 'icon': 'flags/XLeoX.png', 'name': 'XLeoX', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season14', 'icon': 'flags/season14.png', 'name': 'Сезон Технологий', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'NA', 'icon': 'flags/NA.png', 'name': 'Рейтинг это просто цифры', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'fox1', 'icon': 'flags/fox1.png', 'name': 'Лисий хвост', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season15', 'icon': 'flags/season15.png', 'name': 'Сезон Колдовства', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'season16', 'icon': 'flags/season16.png', 'name': 'Сезон Прогресса', 'type': 'customFlags' },
        { 'categoryId': 1, 'externalId': 'default_flag', 'icon': 'flags/default.png', 'name': 'Неизвестный флаг', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'andorra', 'icon': 'flags/andorra.png', 'name': 'Андорра', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'albania', 'icon': 'flags/albania.png', 'name': 'Албания', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'armenia', 'icon': 'flags/armenia.png', 'name': 'Армения', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'argentina', 'icon': 'flags/argentina.png', 'name': 'Аргентина', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'austria', 'icon': 'flags/austria.png', 'name': 'Австрия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'australia', 'icon': 'flags/australia.png', 'name': 'Австралия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'azerbaijan', 'icon': 'flags/azerbaijan.png', 'name': 'Азербайджан', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'bosnia_and_herzegovina', 'icon': 'flags/bosnia_and_herzegovina.png', 'name': 'Босния и Герцеговина', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'belgium', 'icon': 'flags/belgium.png', 'name': 'Бельгия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'bulgaria', 'icon': 'flags/bulgaria.png', 'name': 'Болгария', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'brazil', 'icon': 'flags/brazil.png', 'name': 'Бразилия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'belarus', 'icon': 'flags/belarus.png', 'name': 'Беларусь', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'canada', 'icon': 'flags/canada.png', 'name': 'Канада', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'switzerland', 'icon': 'flags/switzerland.png', 'name': 'Швейцария', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'cyprus', 'icon': 'flags/cyprus.png', 'name': 'Кипр', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'czech_republic', 'icon': 'flags/czech_republic.png', 'name': 'Чехия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'germany', 'icon': 'flags/germany.png', 'name': 'Германия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'denmark', 'icon': 'flags/denmark.png', 'name': 'Дания', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'estonia', 'icon': 'flags/estonia.png', 'name': 'Эстония', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'spain', 'icon': 'flags/spain.png', 'name': 'Испания', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'finland', 'icon': 'flags/finland.png', 'name': 'Финляндия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'france', 'icon': 'flags/france.png', 'name': 'Франция', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'united_kingdom', 'icon': 'flags/united_kingdom.png', 'name': 'Великобритания', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'georgia', 'icon': 'flags/georgia.png', 'name': 'Грузия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'greece', 'icon': 'flags/greece.png', 'name': 'Греция', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'croatia', 'icon': 'flags/croatia.png', 'name': 'Хорватия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'hungary', 'icon': 'flags/hungary.png', 'name': 'Венгрия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'ireland', 'icon': 'flags/ireland.png', 'name': 'Ирландия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'israel', 'icon': 'flags/israel.png', 'name': 'Израиль', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'iceland', 'icon': 'flags/iceland.png', 'name': 'Исландия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'italy', 'icon': 'flags/italy.png', 'name': 'Италия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'kyrgyzstan', 'icon': 'flags/kyrgyzstan.png', 'name': 'Кыргызстан', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'china', 'icon': 'flags/china.png', 'name': 'Китай', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'kazakhstan', 'icon': 'flags/kazakhstan.png', 'name': 'Казахстан', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'liechtenstein', 'icon': 'flags/liechtenstein.png', 'name': 'Лихтенштейн', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'lithuania', 'icon': 'flags/lithuania.png', 'name': 'Литва', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'luxembourg', 'icon': 'flags/luxembourg.png', 'name': 'Люксембург', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'latvia', 'icon': 'flags/latvia.png', 'name': 'Латвия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'monaco', 'icon': 'flags/monaco.png', 'name': 'Монако', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'moldova', 'icon': 'flags/moldova.png', 'name': 'Молдова', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'montenegro', 'icon': 'flags/montenegro.png', 'name': 'Черногория', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'macedonia', 'icon': 'flags/macedonia.png', 'name': 'Македония', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'malta', 'icon': 'flags/malta.png', 'name': 'Мальта', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'mexico', 'icon': 'flags/mexico.png', 'name': 'Мексика', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'netherlands', 'icon': 'flags/netherlands.png', 'name': 'Нидерланды', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'norway', 'icon': 'flags/norway.png', 'name': 'Норвегия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'new_zealand', 'icon': 'flags/new_zealand.png', 'name': 'Новая Зеландия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'philippines', 'icon': 'flags/philippines.png', 'name': 'Филиппины', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'poland', 'icon': 'flags/poland.png', 'name': 'Польша', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'portugal', 'icon': 'flags/portugal.png', 'name': 'Португалия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'romania', 'icon': 'flags/romania.png', 'name': 'Румыния', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'serbia', 'icon': 'flags/serbia.png', 'name': 'Сербия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'russia', 'icon': 'flags/russia.png', 'name': 'Россия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'sweden', 'icon': 'flags/sweden.png', 'name': 'Швеция', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'slovenia', 'icon': 'flags/slovenia.png', 'name': 'Словения', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'slovakia', 'icon': 'flags/slovakia.png', 'name': 'Словакия', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'san_marino', 'icon': 'flags/san_marino.png', 'name': 'Сан-Марино', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'tajikistan', 'icon': 'flags/tajikistan.png', 'name': 'Таджикистан', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'turkmenistan', 'icon': 'flags/turkmenistan.png', 'name': 'Туркменистан', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'turkey', 'icon': 'flags/turkey.png', 'name': 'Турция', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'ukraine', 'icon': 'flags/ukraine.png', 'name': 'Украина', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'united_states', 'icon': 'flags/united_states_of_america.png', 'name': 'США', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'uzbekistan', 'icon': 'flags/uzbekistan.png', 'name': 'Узбекистан', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'vatican', 'icon': 'flags/vatican_city.png', 'name': 'Ватикан', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'vietnam', 'icon': 'flags/vietnam.png', 'name': 'Вьетнам', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'south_afrika', 'icon': 'flags/south_africa.png', 'name': 'Южная Африка', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'jamaica', 'icon': 'flags/jamaica.png', 'name': 'Ямайка', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'japan', 'icon': 'flags/japan.png', 'name': 'Япония', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'chile', 'icon': 'flags/chili.png', 'name': 'Чили', 'type': 'countryFlags' },
        { 'categoryId': 1, 'externalId': 'mozambique', 'icon': 'flags/Mozambique.png', 'name': 'Мозамбик', 'type': 'countryFlags' },
        
        { 'categoryId': 3, 'name': 'bomber_S1', 'icon': 'hero/65/2.webp' },
    ]
}